apiVersion: v1
kind: Service
metadata:
  name: kubernetes
  namespace: default
spec:
  clusterIP: 16.0.0.1
  ports:
  - port: 443
    targetPort: 6443
    protocol: TCP
    name: https
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kubernetes
  namespace: default
  labels:
    endpointslice.kubernetes.io/skip-mirror: "true"
subsets:
- addresses:
  - ip: 192.168.88.142  # Replace with your HOST_IP
  ports:
  - name: https
    port: 6443
    protocol: TCP
